spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: Courses_Jobs
      repositories:
        type: auto
  datasource:
      url: jdbc:mysql://localhost:3306/handbook_crm
      username: root
      password: root